#!/bin/bash
# Report exclusion pattern leaks as a GitHub Pull Request
# Usage: ./scripts/report-leak.sh [project_path] [top_n]
#
# Prerequisites:
#   - gh CLI installed and authenticated
#   - Fork of idris2-coverage cloned locally
#
# This script:
#   1. Detects leaks in high_impact_targets
#   2. Creates a branch with the leak report
#   3. Opens a PR to the main repo

set -e

PROJECT=${1:-.}
TOP=${2:-1000}
IDRIS2_VERSION=$(idris2 --version 2>/dev/null | head -1 || echo "unknown")
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="leak-report-$TIMESTAMP"

echo "=== idris2-coverage Leak Reporter ==="
echo "Project: $PROJECT"
echo "Idris2: $IDRIS2_VERSION"
echo ""

# Run analysis and capture only JSON
JSON_OUTPUT=$(./build/exec/idris2-cov --json --top $TOP "$PROJECT" 2>&1 | \
  sed -n '/^{/,$p')

if [ -z "$JSON_OUTPUT" ]; then
  echo "ERROR: No JSON output from idris2-cov"
  exit 2
fi

# Extract leaks
LEAKS=$(echo "$JSON_OUTPUT" | \
  jq -r '.high_impact_targets[].funcName' 2>/dev/null | \
  grep -E '^(\{|_builtin\.|prim__|Prelude\.|Data\.|System\.|Control\.|Decidable\.|Language\.|Debug\.)' | \
  sort -u)

if [ -z "$LEAKS" ]; then
  echo "No leaks detected. Nothing to report."
  exit 0
fi

LEAK_COUNT=$(echo "$LEAKS" | wc -l | tr -d ' ')
echo "Found $LEAK_COUNT potential leaks:"
echo "$LEAKS" | while read func; do
  echo "  - $func"
done
echo ""

# Confirm with user
read -p "Create PR to report these leaks? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "Aborted."
  exit 0
fi

# Create branch
echo "Creating branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

# Generate leak report file
REPORT_FILE="leak-reports/$TIMESTAMP.md"
mkdir -p leak-reports

cat > "$REPORT_FILE" << EOF
# Leak Report: $TIMESTAMP

## Environment
- **Idris2 Version**: $IDRIS2_VERSION
- **Project Analyzed**: $PROJECT
- **Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

## Detected Leaks

The following functions appeared in \`high_impact_targets\` but should be excluded:

\`\`\`
$LEAKS
\`\`\`

## Suggested Actions

These patterns should be added to \`src/Coverage/DumpcasesParser.idr\`:

### New Compiler-Generated Patterns
$(echo "$LEAKS" | grep -E '^\{' | sed 's/^/- `/' | sed 's/$/`/' || echo "(none)")

### New Standard Library Modules
$(echo "$LEAKS" | grep -E '^(Prelude\.|Data\.|System\.|Control\.|Decidable\.|Language\.|Debug\.)' | sed 's/\..*/\./' | sort -u | sed 's/^/- `/' | sed 's/$/`/' || echo "(none)")

### New Builtin/Primitive Patterns
$(echo "$LEAKS" | grep -E '^(_builtin\.|prim__)' | sed 's/^/- `/' | sed 's/$/`/' || echo "(none)")

---
*Generated by \`scripts/report-leak.sh\`*
EOF

echo "Generated report: $REPORT_FILE"

# Commit
git add "$REPORT_FILE"
git commit -m "$(cat <<EOF
leak-report: $LEAK_COUNT patterns found with Idris2 $IDRIS2_VERSION

Detected exclusion pattern leaks that need to be added to
src/Coverage/DumpcasesParser.idr

See $REPORT_FILE for details.
EOF
)"

# Push and create PR
echo "Pushing branch..."
git push -u origin "$BRANCH_NAME"

echo "Creating Pull Request..."
gh pr create \
  --title "Leak Report: $LEAK_COUNT patterns (Idris2 $IDRIS2_VERSION)" \
  --body "$(cat <<EOF
## Summary

Detected **$LEAK_COUNT exclusion pattern leaks** when analyzing with Idris2 $IDRIS2_VERSION.

These functions appeared in \`high_impact_targets\` but should be filtered out.

## Leaks Found

\`\`\`
$LEAKS
\`\`\`

## How to Fix

Add the new patterns to \`src/Coverage/DumpcasesParser.idr\`:
- For \`{xyz:N}\` patterns: add to \`isCompilerGenerated\`
- For \`Prelude.*\` etc: add to \`isStandardLibraryFunction\`
- For \`prim__*\`: add to \`isCompilerGenerated\`

See [$REPORT_FILE]($REPORT_FILE) for categorized suggestions.

---
*Generated by \`scripts/report-leak.sh\`*
EOF
)"

echo ""
echo "Done! PR created. Return to main branch:"
echo "  git checkout main"
